import { createServer } from 'node:http';
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { exec } from 'node:child_process';
import { downloadXmltvUrl, parseXmltvString } from './fetch.js';

const PORT = 3737;
const ALLOWLIST_PATH = 'config/channels-allowlist.json';
const SELECTED_PATH  = 'config/channels-selected.json';

// ─── Main ────────────────────────────────────────────────────────────────────

async function main() {
  const epgUrl = process.env.PROVIDER_EPG_URL;
  if (!epgUrl) {
    console.error('ERROR: PROVIDER_EPG_URL env var not set');
    console.error('Usage: PROVIDER_EPG_URL="http://host/xmltv.php?username=X&password=Y" node src/selector.js');
    process.exit(1);
  }

  console.log('[selector] Fetching provider EPG...');
  const xml = await downloadXmltvUrl(epgUrl, false);
  const { channels: epgChannels } = parseXmltvString(xml);
  console.log(`[selector] Parsed ${epgChannels.length} channels`);

  // Normalize to UI channel format
  const channels = epgChannels
    .filter(ch => ch.id)
    .map(ch => ({
      tvgId:      ch.id,
      tvgName:    ch.displayName || ch.id,
      tvgLogo:    ch.icon || '',
      groupTitle: inferGroup(ch.id, ch.displayName || ''),
      displayName: ch.displayName || ch.id,
    }));

  // Sort by group then name
  channels.sort((a, b) => a.groupTitle.localeCompare(b.groupTitle) || a.tvgName.localeCompare(b.tvgName));

  const prevSelected = existsSync(SELECTED_PATH)
    ? JSON.parse(readFileSync(SELECTED_PATH, 'utf8'))
    : { selected: [], favorites: [] };

  // Pre-select channels currently in allowlist
  const allowlist = existsSync(ALLOWLIST_PATH)
    ? JSON.parse(readFileSync(ALLOWLIST_PATH, 'utf8'))
    : { channels: [] };
  const allowlistIds = new Set(allowlist.channels.map(c => c['tvg-id']));
  const prevSet = new Set([...(prevSelected.selected || []), ...allowlistIds]);

  const html = buildHtml(channels, { selected: [...prevSet], favorites: prevSelected.favorites || [] });

  const server = createServer((req, res) => {
    if (req.method === 'GET' && req.url === '/') {
      res.writeHead(200, { 'Content-Type': 'text/html; charset=utf-8' });
      res.end(html);
      return;
    }
    if (req.method === 'POST' && req.url === '/save') {
      let body = '';
      req.on('data', c => body += c);
      req.on('end', () => {
        try {
          const { selected, favorites } = JSON.parse(body);
          saveSelection(channels, selected, favorites);
          res.writeHead(200, { 'Content-Type': 'application/json' });
          res.end(JSON.stringify({ ok: true, count: selected.length, favCount: favorites.length }));
        } catch (err) {
          res.writeHead(400);
          res.end(JSON.stringify({ error: err.message }));
        }
      });
      return;
    }
    res.writeHead(404);
    res.end();
  });

  server.listen(PORT, '127.0.0.1', () => {
    const url = `http://localhost:${PORT}`;
    console.log(`\n[selector] ✓ Ready at ${url}\n`);
    const open = process.platform === 'win32' ? `start ${url}` : process.platform === 'darwin' ? `open ${url}` : `xdg-open ${url}`;
    exec(open);
  });
}

// ─── Category inference from channel ID / name ───────────────────────────────

function inferGroup(id, name) {
  const s = (id + ' ' + name).toLowerCase();
  if (/espn|fox.*sport|nfl|nba|mlb|nhl|bein.*sport|golf|tennis|soccer|futbol|deport|tudn|wwe|ufc|fight|wrestling|sport|racing|nascar|f1\b|serie.*a|liga|premier|laliga/.test(s)) return 'Sports';
  if (/hbo|showtime|starz|cinemax|\bmax\b|amc|tcm|ifc|epix|lifetime|hallmark|syfy|tmc|mgm|sundance|cine|movie|film/.test(s)) return 'Movies';
  if (/\bcnn\b|msnbc|fox.*news|bbc.*news|nbc.*news|abc.*news|cbs.*news|newsmax|oann|one america/.test(s)) return 'News';
  if (/wscv|wnju|wapa|wipr|wkaq|teleonce|wapa|canal\s*[0-9]/.test(s)) return 'Puerto Rico';
  if (/\.es\b|spain|espa[nñ]/.test(s)) return 'Spain';
  return 'General';
}

// ─── Save Selection ──────────────────────────────────────────────────────────

function saveSelection(allChannels, selectedIds, favoriteIds) {
  const selectedSet = new Set(selectedIds);

  writeFileSync(SELECTED_PATH, JSON.stringify({ selected: selectedIds, favorites: favoriteIds }, null, 2));
  console.log(`[selector] Saved: ${selectedIds.length} channels, ${favoriteIds.length} favorites`);

  // Update EPG allowlist
  const newAllowlist = {
    _comment: `Generated by selector on ${new Date().toISOString().slice(0, 10)}`,
    channels: allChannels
      .filter(ch => selectedSet.has(ch.tvgId))
      .map(ch => ({ 'tvg-id': ch.tvgId, category: inferGroup(ch.tvgId, ch.tvgName).toLowerCase().replace(/ /g, '-') })),
  };
  writeFileSync(ALLOWLIST_PATH, JSON.stringify(newAllowlist, null, 2));
  console.log(`[selector] Updated ${ALLOWLIST_PATH} (${newAllowlist.channels.length} entries)`);
}

// ─── HTML Builder ────────────────────────────────────────────────────────────

function buildHtml(channels, prevSelected) {
  const prevSet  = new Set(prevSelected.selected || []);
  const prevFavs = new Set(prevSelected.favorites || []);

  // Group channels
  const groups = {};
  for (const ch of channels) {
    if (!groups[ch.groupTitle]) groups[ch.groupTitle] = [];
    groups[ch.groupTitle].push(ch);
  }

  const channelsJson  = JSON.stringify(channels);
  const prevSetJson   = JSON.stringify([...prevSet]);
  const prevFavsJson  = JSON.stringify([...prevFavs]);
  const totalChannels = channels.length;

  // Build groups HTML
  let groupsHtml = '';
  for (const [group, chs] of Object.entries(groups)) {
    const rows = chs.map(ch => {
      const checked = prevSet.has(ch.tvgId) ? 'checked' : '';
      const starred = prevFavs.has(ch.tvgId) ? 'starred' : '';
      const logo = ch.tvgLogo ? `<img src="${escHtml(ch.tvgLogo)}" onerror="this.style.display='none'" loading="lazy">` : '<span class="no-logo"></span>';
      const name = escHtml(ch.displayName || ch.tvgName);
      const tvgId = escHtml(ch.tvgId);
      return `<label class="ch-row" data-id="${tvgId}" data-name="${name.toLowerCase()}">
        <input type="checkbox" class="ch-cb" data-id="${tvgId}" ${checked}>
        ${logo}
        <span class="ch-name">${name}</span>
        <span class="ch-id">${tvgId}</span>
        <span class="fav-btn ${starred}" data-id="${tvgId}" title="Agregar a Favoritos">★</span>
      </label>`;
    }).join('\n');

    const safeGroup = escHtml(group);
    groupsHtml += `
    <div class="group" data-group="${safeGroup}">
      <div class="group-header" onclick="toggleGroup(this)">
        <input type="checkbox" class="group-cb" onclick="event.stopPropagation();toggleGroupCb(this)" title="Seleccionar todo el grupo">
        <span class="arrow">▼</span>
        <span class="group-name">${safeGroup}</span>
        <span class="group-count">(${chs.length})</span>
      </div>
      <div class="group-body">${rows}</div>
    </div>`;
  }

  return `<!DOCTYPE html>
<html lang="es">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>PRDigitalTV — Channel Selector</title>
<style>
*{box-sizing:border-box;margin:0;padding:0}
body{background:#0d0d0d;color:#e2e8f0;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;font-size:14px}
#header{position:sticky;top:0;z-index:100;background:#111827;border-bottom:2px solid #e63946;padding:12px 16px}
.header-top{display:flex;align-items:center;gap:12px;margin-bottom:10px}
.header-top h1{font-size:18px;font-weight:900;color:#e63946;white-space:nowrap}
#search{flex:1;background:#1f2937;border:1px solid #374151;border-radius:8px;padding:8px 12px;color:#e2e8f0;font-size:14px;outline:none}
#search:focus{border-color:#e63946}
.header-actions{display:flex;flex-wrap:wrap;gap:6px}
button{padding:6px 12px;border-radius:6px;border:none;cursor:pointer;font-size:13px;font-weight:600;transition:opacity .15s}
button:hover{opacity:.85}
.btn-primary{background:#e63946;color:#fff}
.btn-secondary{background:#1f2937;color:#e2e8f0;border:1px solid #374151}
.btn-gold{background:#d97706;color:#fff}
#counter{color:#94a3b8;font-size:13px;white-space:nowrap;margin-left:auto}
#content{padding:8px 16px 100px}
.group{margin-bottom:4px;border-radius:8px;overflow:hidden;border:1px solid #1f2937}
.group-header{display:flex;align-items:center;gap:8px;padding:10px 14px;background:#1a1a2e;cursor:pointer;user-select:none}
.group-header:hover{background:#1e2340}
.group-cb{width:16px;height:16px;cursor:pointer;accent-color:#e63946}
.arrow{font-size:11px;color:#64748b;transition:transform .2s;width:12px}
.group-name{font-weight:700;color:#e2e8f0}
.group-count{color:#64748b;font-size:12px}
.group-body{display:flex;flex-direction:column}
.group.collapsed .group-body{display:none}
.group.collapsed .arrow{transform:rotate(-90deg)}
.ch-row{display:flex;align-items:center;gap:8px;padding:6px 14px;cursor:pointer;border-top:1px solid #111827;transition:background .1s}
.ch-row:hover{background:#111827}
.ch-row.hidden{display:none}
.ch-row input[type=checkbox]{width:16px;height:16px;cursor:pointer;accent-color:#e63946;flex-shrink:0}
.ch-row img{width:32px;height:20px;object-fit:contain;flex-shrink:0;background:#000;border-radius:3px}
.no-logo{width:32px;height:20px;flex-shrink:0;background:#1f2937;border-radius:3px}
.ch-name{flex:1;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-size:13px}
.ch-id{color:#4b5563;font-size:11px;flex-shrink:0;font-family:monospace}
.fav-btn{font-size:16px;color:#374151;cursor:pointer;flex-shrink:0;padding:0 2px;transition:color .15s}
.fav-btn:hover{color:#f59e0b}
.fav-btn.starred{color:#f59e0b}
#save-bar{position:fixed;bottom:0;left:0;right:0;background:#111827;border-top:2px solid #e63946;padding:12px 16px;display:flex;align-items:center;gap:12px}
#save-btn{background:#e63946;color:#fff;padding:10px 28px;font-size:15px;border-radius:8px;border:none;cursor:pointer;font-weight:700}
#save-btn:hover{background:#c81e2a}
#save-status{color:#34d399;font-size:13px;display:none}
#fav-count{color:#f59e0b;font-size:13px}
.shift-hint{color:#64748b;font-size:12px;margin-left:auto}
</style>
</head>
<body>

<div id="header">
  <div class="header-top">
    <h1>PRDigitalTV · Channel Selector</h1>
    <input id="search" type="text" placeholder="Buscar canal o ID..." oninput="filterChannels(this.value)">
    <span id="counter">0 / ${totalChannels}</span>
  </div>
  <div class="header-actions">
    <button class="btn-primary" onclick="selectMatchingSearch()">✓ Seleccionar coincidencias</button>
    <button class="btn-secondary" onclick="selectAll()">✓ Todo</button>
    <button class="btn-secondary" onclick="deselectAll()">✗ Ninguno</button>
    <button class="btn-secondary" onclick="invertAll()">⇄ Invertir</button>
    <button class="btn-gold" onclick="collapseAll()">Colapsar todo</button>
    <button class="btn-secondary" onclick="expandAll()">Expandir todo</button>
  </div>
</div>

<div id="content">${groupsHtml}</div>

<div id="save-bar">
  <button id="save-btn" onclick="saveSelection()">💾 Guardar Selección</button>
  <span id="sel-summary">0 canales seleccionados</span>
  <span id="fav-count">★ 0 favoritos</span>
  <span class="shift-hint">Tip: Shift+click para rango · Clic en ★ para Favoritos</span>
  <span id="save-status">✓ Guardado exitosamente</span>
</div>

<script>
const ALL_CHANNELS = ${channelsJson};
const prevSelected = new Set(${prevSetJson});
const favorites = new Set(${prevFavsJson});
let lastChecked = null;

window.addEventListener('DOMContentLoaded', () => {
  updateCounter();
  syncGroupCheckboxes();

  document.querySelectorAll('.ch-cb').forEach(cb => {
    cb.addEventListener('click', e => {
      if (e.shiftKey && lastChecked) {
        const all = [...document.querySelectorAll('.ch-cb:not(.hidden-cb)')];
        const a = all.indexOf(lastChecked), b = all.indexOf(cb);
        const [lo, hi] = [Math.min(a,b), Math.max(a,b)];
        const state = lastChecked.checked;
        all.slice(lo, hi+1).forEach(c => { c.checked = state; });
      }
      lastChecked = cb;
      syncGroupCheckboxes();
      updateCounter();
    });
  });

  document.querySelectorAll('.fav-btn').forEach(btn => {
    btn.addEventListener('click', e => {
      e.preventDefault(); e.stopPropagation();
      const id = btn.dataset.id;
      if (favorites.has(id)) { favorites.delete(id); btn.classList.remove('starred'); }
      else { favorites.add(id); btn.classList.add('starred'); }
      updateCounter();
    });
  });

  document.querySelectorAll('.ch-cb').forEach(cb => {
    if (prevSelected.has(cb.dataset.id)) cb.checked = true;
  });
  syncGroupCheckboxes();
  updateCounter();
});

function selectAll() {
  document.querySelectorAll('.ch-row:not(.hidden) .ch-cb').forEach(cb => cb.checked = true);
  syncGroupCheckboxes(); updateCounter();
}
function deselectAll() {
  document.querySelectorAll('.ch-cb').forEach(cb => cb.checked = false);
  syncGroupCheckboxes(); updateCounter();
}
function invertAll() {
  document.querySelectorAll('.ch-row:not(.hidden) .ch-cb').forEach(cb => cb.checked = !cb.checked);
  syncGroupCheckboxes(); updateCounter();
}
function selectMatchingSearch() {
  const q = document.getElementById('search').value.trim().toLowerCase();
  if (!q) return;
  document.querySelectorAll('.ch-row:not(.hidden) .ch-cb').forEach(cb => cb.checked = true);
  syncGroupCheckboxes(); updateCounter();
}
function collapseAll() {
  document.querySelectorAll('.group').forEach(g => g.classList.add('collapsed'));
}
function expandAll() {
  document.querySelectorAll('.group').forEach(g => g.classList.remove('collapsed'));
}
function toggleGroup(header) {
  header.closest('.group').classList.toggle('collapsed');
}
function toggleGroupCb(cb) {
  const body = cb.closest('.group').querySelector('.group-body');
  body.querySelectorAll('.ch-row:not(.hidden) .ch-cb').forEach(c => c.checked = cb.checked);
  updateCounter();
}

function filterChannels(q) {
  const term = q.trim().toLowerCase();
  document.querySelectorAll('.group').forEach(group => {
    let visible = 0;
    group.querySelectorAll('.ch-row').forEach(row => {
      const match = !term || row.dataset.name.includes(term) || row.dataset.id.toLowerCase().includes(term);
      row.classList.toggle('hidden', !match);
      if (match) visible++;
    });
    group.style.display = visible === 0 ? 'none' : '';
  });
  syncGroupCheckboxes();
}

function syncGroupCheckboxes() {
  document.querySelectorAll('.group').forEach(group => {
    const cbs = [...group.querySelectorAll('.ch-row:not(.hidden) .ch-cb')];
    const gcb = group.querySelector('.group-cb');
    if (!gcb || !cbs.length) return;
    const checkedCount = cbs.filter(c => c.checked).length;
    gcb.checked = checkedCount === cbs.length;
    gcb.indeterminate = checkedCount > 0 && checkedCount < cbs.length;
  });
}

function updateCounter() {
  const total = document.querySelectorAll('.ch-cb').length;
  const checked = [...document.querySelectorAll('.ch-cb')].filter(c => c.checked).length;
  document.getElementById('counter').textContent = checked + ' / ' + total;
  document.getElementById('sel-summary').textContent = checked + ' canales seleccionados';
  document.getElementById('fav-count').textContent = '★ ' + favorites.size + ' favoritos';
}

async function saveSelection() {
  const selected = [...document.querySelectorAll('.ch-cb:checked')].map(c => c.dataset.id);
  const btn = document.getElementById('save-btn');
  const status = document.getElementById('save-status');
  btn.disabled = true;
  btn.textContent = 'Guardando...';
  try {
    const res = await fetch('/save', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ selected, favorites: [...favorites] }),
    });
    const data = await res.json();
    if (data.ok) {
      status.style.display = 'inline';
      btn.textContent = '✓ Guardado (' + data.count + ' canales)';
      setTimeout(() => { status.style.display = 'none'; btn.textContent = '💾 Guardar Selección'; btn.disabled = false; }, 3000);
    }
  } catch(e) {
    btn.textContent = '❌ Error — intenta de nuevo';
    btn.disabled = false;
  }
}
</script>
</body>
</html>`;
}

function escHtml(str) {
  return String(str).replace(/&/g, '&amp;').replace(/"/g, '&quot;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

main().catch(err => { console.error('[selector] Fatal:', err); process.exit(1); });
